name: Java CI with Maven

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build and deploy snapshot
      run: ./mvnw -B deploy --file pom.xml -s settings.xml -DcentralOssrhUsername=${{ secrets.CENTRAL_OSSRH_USERNAME }} -DcentralOssrhPassword=${{ secrets.CENTRAL_OSSRH_PASSWORD }}
